version: 2.1
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t my-custom-image -f DockerFile1 .
      - run:
          name: Run Docker container
          command: |
            docker run -t -v /var/run/docker.sock:/var/run/docker.sock my-custom-image:latest
