version: 2.1
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 
      - run:
          name: Build Docker image
          command: |
            docker build -t my-custom-image -f DockerFile1 .
      - run:
          name: Run Docker container
          command: |
            docker run -t my-custom-image



# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.7 
#     steps:
#       - checkout

#       # Enable Remote Docker
#       - setup_remote_docker:
#           version: 20.10.7 
#       - run:
#           name: Pull Docker Image
#           command: docker pull ojaswa1942/privado-cli-wrapper:latest

#       # Run the Docker container
#       - run:
#           name: Run Docker container
#           command: docker run -t -v /var/run/docker.sock:/var/run/docker.sock -v /root/.cache:/root/.cache -v /root/.privado:/root/.privado -v $(pwd):$(pwd) ojaswa1942/privado-cli-wrapper:latest --overwrite --upload $(pwd)
