
name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull ojaswa1942/privado-cli-wrapper:latest

      - name: Run Docker Container
        run: |
          docker run -t -v /var/run/docker.sock:/var/run/docker.sock -v /root/.cache:/root/.cache -v /root/.privado:/root/.privado -v $(pwd):$(pwd) ojaswa1942/privado-cli-wrapper:latest --overwrite --upload $(pwd)


